### ISSUE TITLE
Disable Recommendations | Very Important Feature In The World Full Of Distractions

### ISSUE THREAD

**Issue by prajjwalgeek** [revanced/revanced-suggestions#747] opened 2022-11-05 14:38 UTC
### Discussed in https://github.com/orgs/revanced/discussions/146

<div type='discussions-op-text'>

<sup>Originally posted by **MSOB7YY** April  2, 2022</sup>
option to disable recommendations especially when playing videos from playlist

_buT WhY_: 
1. Decrease Distraction
2. Save Data (thumbnail loading makes the video lags when on low connection speed 💀)
3. It's very difficult to study long lectures with so many appealing videos recommended while important videos are often boring.</div>

**Comment by oSumAtrIX** [comment] 2022-11-05 14:46
Dupe of #146.

**Closed by oSumAtrIX** 2022-11-05 14:46 UTC
